export const AppColors = {
  primaryColor: '#7F3DFF',
  primaryTextColor: '#212325',
  secondaryTextColor: '#91919F',
  lightPurple: '#EEE5FF',
  cultured: '#F6F6F6',
  headerTitle: '#212325',
  white: '#FFFFFF',
  lavender: '#EEE5FF',
  mistyRose: '#FFE2E4',
  screenColor: '#FFFFFF',
  borderColor: '#F1F1FA',
  whiteText: '#FCFCFC',
  titleColor: '#292B2D',
};
