export const ImagesAssets = {
  illustration1: require('./Illustration-1.png'),
  illustration2: require('./Illustration-2.png'),
  illustration3: require('./Illustration-3.png'),
  bg: require('./BG.png'),
  SentEmail: require('./sent-email.png'),
  Success: require('./success.png'),
  Momo: require('./momo.png'),
  Vnpay: require('./vnpay.png'),
  Zalopay: require('./zalopay.png'),
  Vietcombank: require('./vietcombank.png'),
  Acbbank: require('./acbbank.png'),
  Agribank: require('./agribank.png'),
  BIDV: require('./bidv.png'),
  Mbbank: require('./mbbank.png'),
  Sacombank: require('./sacombank.png'),
  Scbbank: require('./scbbank.png'),
  Techcombank: require('./techcombank.png'),
  Vietinbank: require('./vietinBank.png'),
  Vpbank: require('./vpbank.png'),
  chart: require('./Graph.png'),
};
